### ISSUE TITLE
Icons mostly missing for non-installed apps

### ISSUE THREAD

**Issue by pabloyoyoista** [Cogitri/gnome-software-plugin-apk#18]
When looking for apps or in the initial window, icons for all apps are missing. 

Debugging, I have found the following:

```
Looking for icon for de.haeckerfelix.Shortwave, at size 32×1, with fallback (null)
20:21:09:0437 Gs        Considering icon of type GFileIcon (/var/cache/app-info/icons/alpinelinux-edge-community/64x64/
gnome-shortwave_de.haeckerfelix.Shortwave.png), width 64×1
20:21:09:0437 GLib-GIO g_input_stream_read: assertion 'G_IS_INPUT_STREAM (stream)' failed
20:21:09:0437 Gs  pixbuf couldn’t be loaded, so no key colors
```

The folder `/var/cache/app-info/icons` does not exist and it looks like the appstream data missed to generate some icons. In https://appstream.alpinelinux.org/data/edge/main/ there is only `icons-main-128x128.tar.gz` and `icons-main-aarch64-64x64.tar.gz`

**Comment by Cogitri** [comment]
Yeah, for some reason asgen only generates the icon pack for changed packages, but I never got around to figuring out why it does that.

**Comment by pablofsf** [comment]
I guess that is in alpine infra? One good possibility for improvement actually comes from the quality of the appstream data. If we figure out a way for screenshots and icons to show reliably, then it should look much better :)

**Comment by pabloyoyoista** [comment]
This is fixed with latest upstream changes.
