### ISSUE TITLE
Codestyle of GNOME Software is not honored

### ISSUE THREAD

**Issue by DylanVanAssche** [Cogitri/gnome-software-plugin-apk#40]
It seems that the codestyle (tabs, no brackets for if cases with one line, etc.) of GNOME Software is not honored here.
Is that on purpose?

If we ever want to upstream it, I think this will be a requirement.

**Comment by Cogitri** [comment]
Probably - we can run clang-format at that point though. I‘d rather not reformat now so that git blame stays useful

**Comment by DylanVanAssche** [comment]
@Cogitri So if I make changes I shouldn't care much, just follow the code style we currently have?

**Comment by Cogitri** [comment]
Yup 👍

**Comment by pabloyoyoista** [comment]
There's the clang-format and CI checks against it, so it's just a matter of setting it up and it'll do the formatting for you :)

**Comment by DylanVanAssche** [comment]
Alright! Thanks!
