### ISSUE TITLE
Switch apk-polkit-rs operations to async

### ISSUE THREAD

**Issue by DylanVanAssche** [Cogitri/gnome-software-plugin-apk#44]
Currently, apk-polkit-rs operations are executed synchronous.
This blocks the UI thread and makes the whole thing unresponsive until the task is completed.

With the refactoring in GNOME Software 42, we can make use of GTasks to run most operations asynchronous.
However, our operations is still synchronous so we don't benefit of this refactoring yet, let's change that with this issue!

**Comment by pabloyoyoista** [comment]
Currently, this is quite important for the refresh metadata call. That DBus call does network connections, and as such it could take a long time. Currently, it is blocking the main thread, which could lead to big issues.
