### ISSUE TITLE
Changes in 44

### ISSUE THREAD

**Issue by pabloyoyoista** [Cogitri/gnome-software-plugin-apk#69]
For the record and if somebody wants to look at it:

- [ ] Add a way to show only open-source apps. We have to make sure that ours apps do not get filtered! https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1515
- [ ] The query for such apps: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1618
- [x] Preparation for async updates apps: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1615
- [x] Async updates apps: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1616
  - [x] Also port tests. Example: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1616/diffs?commit_id=3519307cf05e82430df21e0ce43a1b64b2fc15d0

This is a pretty short one, yay!

**Comment by Newbytee** [comment]
> Async updates apps, although not sure if it will make it to 44: https://gitlab.gnome.org/GNOME/gnome-software/-/merge_requests/1616

Looks like it did make it.

**Comment by andypost** [comment]
there's https://gitlab.gnome.org/GNOME/gnome-software/-/tags/44.1

**Comment by pabloyoyoista** [comment]
Thanks! Though those are not allowed to do API changes, so nothing else should be needed to be added to the list at the top.
